### ISSUE TITLE
Import("env") on windows.py

### ISSUE THREAD

**Issue by DJOPRO-STUDIO** [paxo-phone/PaxOS-9#60]
![image](https://github.com/paxo-phone/PaxOS-9/assets/128752386/6f3031bf-5a29-4783-b3b5-5630c0ba3076)

**Comment by slohwnix** [comment]
J'ai fait un pull requets pour le patch

**Comment by Charlito33** [comment]
Faudrait apprendre à utiliser platformIO au lieu de lancer des scripts python aléatoirement.
