### ISSUE TITLE
commande storage:file(path,bool) ne marche pas car le mode bool a un probleme

### ISSUE THREAD

**Issue by DJOPRO-STUDIO** [paxo-phone/PaxOS-9#61]
![image](https://github.com/paxo-phone/PaxOS-9/assets/128752386/cada9b6f-bad2-4f2b-bc2b-a755c0027f36)

**Comment by Charlito33** [comment]
On peut voir ton code ?

**Comment by DJOPRO-STUDIO** [comment]
ok
`function run()
    file = storage:file("text.txt",false)
    print(file:read())
end`

**Comment by b5i** [comment]
Si tu vas dans lua/src/lua_storage.cpp/hpp et que tu remplaces tous les storage::Path par des std::string (en changeant bien les implementations dans le .cpp pour convertir la string en Path) est-ce que ça fonctionne ?

**Comment by paxo-rch** [comment]
C'est corrigé, tu peux a la place du bool utiliser READ, WRITE, APPEND comme 2 eme argument
