### ISSUE TITLE
Lua "gui:vlist" ne scrolle pas mais dépasse de l'écran 

### ISSUE THREAD

**Issue by DJOPRO-STUDIO** [paxo-phone/PaxOS-9#63]
quand je met le gui:vlist(win,0,0,0,0) avec les dimmension de je veux , il ne scroll pas quand il a beaucoup d'item qui depasse l'écrant

**Comment by paxo-rch** [comment]
oui c'est prévu mais pas dev pour le moment

**Comment by paxo-rch** [comment]
c'est corrigé sur ma branche, ce sera bon dans quelques minutes
